services:
    postgresdb:
        image: postgres:15
        container_name: postgresdb
        restart: on-failure
        env_file: ./.env
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        ports:
            - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
        volumes:
            - mini-social-web-react_postgres-data:/var/lib/postgresql/data
volumes:
    mini-social-web-react_postgres-data:
        external: true
