services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"  
    depends_on:
      - postgresdb
    env_file:
      - ./backend/.env

  postgresdb:
    image: postgres:15
    container_name: postgresdb
    restart: always
    env_file: ./.env
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: